{"name": "Получение заказов авторизованного пользователя", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('user_token', <FixtureRequest for <Function test_get_orders_with_auth>>)", "trace": "file /Users/verazelikson/Desktop/Diplom_Vera_Zelikson_13/Diplom_2/tests/test_get_users_orders.py, line 17\n      @allure.title('Получение заказов авторизованного пользователя')\n      def test_get_orders_with_auth(self, user_token):\nE       fixture 'user_token' not found\n>       available fixtures: _session_faker, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, faker, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/Users/verazelikson/Desktop/Diplom_Vera_Zelikson_13/Diplom_2/tests/test_get_users_orders.py:17"}, "start": 1730321812735, "stop": 1730321812735, "uuid": "2df4f6b1-4e6e-4c5c-b2ec-85fc53003572", "historyId": "9677d02208d5ee33317d6863bd693465", "testCaseId": "9677d02208d5ee33317d6863bd693465", "fullName": "tests.test_get_users_orders.TestGetUserOrders#test_get_orders_with_auth", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_users_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "Veras-MacBook-Pro.local"}, {"name": "thread", "value": "34066-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_users_orders"}]}